[project]
name = "emacs-mcp-server"
version = "0.1.0"
description = "MCP server for controlling Emacs via emacsclient"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.1.0",
]

[project.scripts]
emacs-mcp-server = "server:main"

[tool.hatch.build.targets.wheel]
packages = ["."]
only-include = ["server.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
