[project]
name = "emacs-mcp-server"
version = "0.1.0"
description = "Simple MCP server for controlling and interacting with Emacs remotely"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.9.0"
]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
emacs-mcp-server = "emacs_mcp_server:main"
